# Generated by Django 5.2.1 on 2025-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='purpose',
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(default='type', max_length=100),
            preserve_default=False,
        ),
    ]
