# Generated by Django 5.2.1 on 2025-05-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='organizations', to='core.character')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
