# Generated by Django 5.2.1 on 2025-05-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organization_purpose_organization_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='notes',
            new_name='description',
        ),
    ]
