# Generated by Django 5.2.1 on 2025-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bio_character_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='places', to='core.character'),
        ),
    ]
