# Generated by Django 5.2.1 on 2025-05-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='plot_points', to='core.character')),
                ('organizations', models.ManyToManyField(blank=True, related_name='plot_points', to='core.organization')),
                ('places', models.ManyToManyField(blank=True, related_name='plot_points', to='core.place')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_points', to='core.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
