# Generated by Django 5.2.1 on 2025-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_place_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='core.place'),
        ),
    ]
