# Generated by Django 5.2.1 on 2025-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chapter_plotpoint_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=1),
        ),
    ]
