# Generated by Django 5.2.1 on 2025-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_chapter_options_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='core.character'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='core.organization'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='core.place'),
        ),
    ]
