# Generated by Django 5.2.1 on 2025-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chapter_characters_chapter_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True, help_text='Outline notes about this chapter'),
        ),
    ]
