# Generated by Django 5.2.1 on 2025-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chapter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
