# Generated by Django 5.2.1 on 2025-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_genre_project_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True, help_text='Enter character traits, separated by commas', null=True),
        ),
    ]
