# Generated by Django 5.2.1 on 2025-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_character_age_character_appearance_character_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='core_premise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_themes',
            field=models.TextField(blank=True, help_text='Enter key themes, separated by commas', null=True),
        ),
    ]
