# Generated by Django 5.2.1 on 2025-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_core_premise_project_key_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_arc_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='external_conflict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='internal_conflict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='key_motivations',
            field=models.TextField(blank=True, help_text='Enter key motivations, separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_goals',
            field=models.TextField(blank=True, help_text='Enter secondary goals, separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True, help_text='Enter strengths, separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='Enter weaknesses, separated by commas', null=True),
        ),
    ]
