# Generated by Django 5.2.1 on 2025-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_core_premise_project_key_themes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('project', 'title')},
        ),
    ]
