# Generated by Django 5.2.1 on 2025-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_character_character_arc_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotpoint',
            name='description',
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='character_development_achieved',
            field=models.TextField(blank=True, help_text='How do characters develop or change?', null=True),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='conflict_introduced_or_escalated',
            field=models.TextField(blank=True, help_text='What conflict is introduced or escalated?', null=True),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='information_revealed_to_reader',
            field=models.TextField(blank=True, help_text='What new information is revealed to the reader?', null=True),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='key_events',
            field=models.TextField(blank=True, help_text='Key events that occur in this plot point.', null=True),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='narrative_function',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='key_motivations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='secondary_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
