# Generated by Django 5.2.1 on 2025-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_plotpoint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='atmosphere_keywords',
            field=models.TextField(blank=True, help_text='Keywords for mood, feeling, ambiance.', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sensory_details_keywords',
            field=models.TextField(blank=True, help_text='Keywords for sight, sound, smell, touch, taste.', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='strategic_importance_or_plot_relevance',
            field=models.TextField(blank=True, help_text='Why is this place important to the story?', null=True),
        ),
    ]
