# Generated by Django 5.2.1 on 2025-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_place_atmosphere_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='goals_and_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hierarchy_and_membership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='modus_operandi_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='relationships_with_other_entities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='atmosphere_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='sensory_details_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='strategic_importance_or_plot_relevance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='character_development_achieved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='conflict_introduced_or_escalated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='information_revealed_to_reader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='key_events',
            field=models.TextField(blank=True, null=True),
        ),
    ]
