# Generated by Django 5.2.1 on 2025-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_goals_and_objectives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sensory_details_keywords',
            field=models.TextField(blank=True, help_text='Enter keywords separated by semicolons (e.g., hearthwood smoke; perpetual twilight; distant chanting)', null=True),
        ),
    ]
