# Generated by Django 5.2.1 on 2025-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_place_sensory_details_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='external_conflict',
            field=models.TextField(blank=True, help_text='Describe external conflicts, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='internal_conflict',
            field=models.TextField(blank=True, help_text='Describe internal conflicts, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='key_motivations',
            field=models.TextField(blank=True, help_text='Enter key motivations, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='secondary_goals',
            field=models.TextField(blank=True, help_text='Enter secondary goals, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True, help_text='Enter strengths, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True, help_text='Enter character traits, separated by semicolons (e.g., Brave; Loyal; Quick-tempered)', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='Enter weaknesses, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goals_and_objectives',
            field=models.TextField(blank=True, help_text='Describe goals and objectives, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hierarchy_and_membership',
            field=models.TextField(blank=True, help_text='Describe hierarchy and membership details, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modus_operandi_keywords',
            field=models.TextField(blank=True, help_text='Enter modus operandi keywords, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='relationships_with_other_entities',
            field=models.TextField(blank=True, help_text='Describe relationships with other entities, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='atmosphere_keywords',
            field=models.TextField(blank=True, help_text='Enter atmosphere keywords, separated by semicolons (e.g., ominous; joyful; tense)', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='strategic_importance_or_plot_relevance',
            field=models.TextField(blank=True, help_text='Describe strategic importance or plot relevance, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='character_development_achieved',
            field=models.TextField(blank=True, help_text='Character development achieved, items separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='conflict_introduced_or_escalated',
            field=models.TextField(blank=True, help_text='Conflict introduced/escalated, items separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='information_revealed_to_reader',
            field=models.TextField(blank=True, help_text='Information revealed, items separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='key_events',
            field=models.TextField(blank=True, help_text='Key events that occur, items separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='narrative_function',
            field=models.TextField(blank=True, help_text='Describe the narrative function, items separated by semicolons', null=True),
        ),
    ]
