# Generated by Django 5.2.1 on 2025-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_character_external_conflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief summary of the place.', null=True),
        ),
    ]
