# Generated by Django 5.2.1 on 2025-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_place_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='internal_dynamics',
            field=models.TextField(blank=True, help_text='Describe internal dynamics, separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
