# Generated by Django 5.2.1 on 2025-05-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_internal_dynamics_alter_project_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True, help_text='Enter character traits, separated by semicolons', null=True),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('project', 'Project'), ('character', 'Character'), ('place', 'Place'), ('organization', 'Organization')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'name', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='CharacterAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='core.attributedefinition')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='core.character')),
            ],
            options={
                'unique_together': {('character', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='core.attributedefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='PlaceAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='core.attributedefinition')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='core.place')),
            ],
            options={
                'unique_together': {('place', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='core.attributedefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'attribute')},
            },
        ),
    ]
