# Generated by Django 5.2.1 on 2025-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_internal_dynamics_alter_project_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='character_thumbnails/'),
        ),
    ]
