# Generated by Django 5.2.1 on 2025-05-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chapter_updated_at_character_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='core_premise',
        ),
        migrations.RemoveField(
            model_name='project',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='project',
            name='key_themes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='style',
        ),
    ]
